### ISSUE TITLE
non-descriptive Error in SHA2 when installing

### ISSUE THREAD

**Issue by abdurrahman-nasr** [chrisnc/tangaroa#1]
I had the following error when installing Tangoroa

cabal: Error: some packages failed to install:
SHA2-0.2.5 failed during the building phase. The exception was:
ExitFailure 1

**Comment by chrisnc** [comment]
I wasn't able to reproduce this exact issue; however, it seems like the SHA2 package is unmaintained and doesn't seem to work with newer versions of all the other dependencies. I switched to https://hackage.haskell.org/package/cryptohash-sha256 which is actively maintained.
