### ISSUE TITLE
Error when compiling the Tangaroa 

### ISSUE THREAD

**Issue by hmhsalama** [chrisnc/tangaroa#2]
I downloaded the last version which modified in 2016 05 30 , but the compilation is not completed and i got :
network-2.6.2.1 failed during the configure step. The exception was: ExitFailure 77  network-2.6.2.1

I use Windows 7 with 64-Bit

**Comment by chrisnc** [comment]
This is not an issue in Tangaroa, but likely in your Haskell or cabal installation. Try building the `network` package with `cabal install network`, which may give more detailed information.
