### ISSUE TITLE
Error when compiling the Tangaroa on Windows7 64-Bit

### ISSUE THREAD

**Issue by hmhsalama** [chrisnc/tangaroa#3]
I have Haskell-platform Version 8.0
and i Downloaded the last Tangaroa-Master in 15 Jun, but when run command "cabal install" on the tangarao.cabal it Replied by the next Error:

cabal: Error: some packages failed to install:
network-2.6.2.1 failed during the configure step. The exception was:
ExitFailure 77

Would you give a hand for this Issue please

**Comment by chrisnc** [comment]
This is a dup of #2. Please refrain from filing issues here that are not related to Tangaroa. If you cannot build the network package on your machine, there may be a misconfiguration or bug there.
